module.exports = {
  username: "",
  password: "",
  submitInfo: 
  {
    "cysjh": '12345678910',
    "jcjgqr": 0, 
    "sfjcjwggry": 0, 
    "szgjcs": "", 
    "szcs": "", 
    "szgj": "", 
    "sfcysjh": "0", 
    "dqszyqfxdj": 3, 
    "dzjkmys": 3, 
    "sffx": "", 
    "nj": "", 
    "njqt": "", 
    "zybj": "", 
    "xslb": "", 
    "sfbys": "0", 
    "cjtw": "", 
    "wjtw": "", 
    "wujtw": "", 
    "sfywcxyxd": "0", 
    "sffdypz": "", 
    "cxsj": "", 
    "fxsj": "", 
    "cxyy": "", 
    "ddd": "", 
    "tjd": "", 
    "cxjtfs": [ ], 
    "cxjtfsqt": "", 
    "ywqtsm": "0", 
    "xxqk": "", 
    "sfjcyqzgfxdq": "0", 
    "sfjtyqzgfxdq": 0, 
    "sfjzxgym": 1, 
    "jzjzj": 1, 
    "wcjzj": 2, 
    "wzjyy": "", 
    "sfnmss": 1, 
    "yjzjqz": 1, 
    "fhjzjqz": 1, 
    "gtshsyqk": [ ], 
    "tw": 2, 
    "sfcxtz": 0, 
    "sfjcbh": 0, 
    "sfcxzysx": 0, 
    "qksm": "", 
    "sfyyjc": 0, 
    "remark": "", 
    "address": "湖南省长沙市岳麓区岳麓街道中南大学本部北校区计算机楼", 
    "geo_api_info": "{\"type\":\"complete\",\"info\":\"SUCCESS\",\"status\":1,\"$Da\":\"jsonp_256210_\",\"position\":{\"Q\":28.1708,\"R\":112.9314,\"lng\":112.9314,\"lat\":28.1708},\"message\":\"Get ipLocation success.Get address success.\",\"location_type\":\"ip\",\"accuracy\":null,\"isConverted\":true,\"addressComponent\":{\"citycode\":\"0731\",\"adcode\":\"430104\",\"businessAreas\":[],\"neighborhoodType\":\"\",\"neighborhood\":\"\",\"building\":\"\",\"buildingType\":\"\",\"street\":\"麓山南路\",\"streetNumber\":\"56号\",\"country\":\"中国\",\"province\":\"湖南省\",\"city\":\"长沙市\",\"district\":\"岳麓区\",\"township\":\"岳麓街道\"},\"formattedAddress\":\"湖南省长沙市岳麓区岳麓街道中南大学本部北校区计算机楼\",\"roads\":[],\"crosses\":[],\"pois\":[]}", 
    "area": "湖南省 长沙市 岳麓区", 
    "province": "湖南省", 
    "city": "长沙市",
    "sfzx": 0, 
    "sfjcwhry": 0, 
    "sfjchbry": 0, 
    "sfcyglq": 0, 
    "gllx": "", 
    "glksrq": "", 
    "jcbhlx": "", 
    "jcbhrq": "", 
    "ismoved": 0, 
    "bztcyy": "", 
    "sftjhb": 0, 
    "sftjwh": 0, 
  }
}